### ISSUE TITLE
And what if the data type allows us to do such operations? These operands are not numbers and should not be able to be used in a calculator class

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks#2]
https://github.com/NikitaZhukovsky/oop-tasks/blob/f69cff3d50b62c5944fadec24b274d7c089757d3/Task_2/calc.py#L2-L6

**Comment by SkrytnayaRediska** [comment]
![Снимок экрана 2024-01-24 в 15 06 12](https://github.com/NikitaZhukovsky/oop-tasks/assets/44698380/a55da122-0e98-41d9-bc53-5ec0929039aa)

**Comment by NikitaZhukovsky** [comment]
Fixed it
