### ISSUE TITLE
And here we go again))

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks#3]
https://github.com/NikitaZhukovsky/oop-tasks/blob/7ecdaf9cff8af2a01ef9364b1f3f9252f708e0d1/Task_3/car.py#L1-L20

Need to add some checks to the init method and setters. A user can set literally whatever he wants, we should not allow to do it. 

![Снимок экрана 2024-01-24 в 15 11 27](https://github.com/NikitaZhukovsky/oop-tasks/assets/44698380/7b8ff3a1-7ca1-4ee6-8ef3-3b7de1b0a525)

**Comment by SkrytnayaRediska** [comment]
![Снимок экрана 2024-01-24 в 15 11 27](https://github.com/NikitaZhukovsky/oop-tasks/assets/44698380/8d6a0bb1-03ab-4ba6-a9df-5b9cfcf2f68b)
sorry, thus picture

**Comment by NikitaZhukovsky** [comment]
Fixed it
