### ISSUE TITLE
Missed one method

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks#6]
https://github.com/NikitaZhukovsky/oop-tasks/blob/7ecdaf9cff8af2a01ef9364b1f3f9252f708e0d1/Task_4/sphere.py#L4-L37
![Снимок экрана 2024-01-24 в 15 18 20](https://github.com/NikitaZhukovsky/oop-tasks/assets/44698380/099cafca-d965-41d6-9cc3-7d5c99ce4177)

**Comment by NikitaZhukovsky** [comment]
Fixed it
