### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/oop-tasks#8]
https://github.com/NikitaZhukovsky/oop-tasks/blob/7753f8969d7e1ee3d835fa79a34ed693b976cce0/Task_5/super_str.py#L2-L7
![Снимок экрана 2024-01-24 в 15 22 22](https://github.com/NikitaZhukovsky/oop-tasks/assets/44698380/d3a24654-2f86-46e5-b28b-5f9f4973c9c9)

**Comment by NikitaZhukovsky** [comment]
Fixed it
